# Generated by Django 3.1.6 on 2021-02-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_following',
            field=models.BooleanField(default=True),
        ),
    ]
