# Generated by Django 3.1.6 on 2021-07-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follow_is_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
